import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css'
import ui from '../../styles/ui.module.css'
import { 
  Alert,
  Button, 
  Checkbox, 
  Form, 
  Input,
  Row,
  Divider,
  Badge,
  Space
} from 'antd';

import { useState } from 'react';


type LayoutType = Parameters<typeof Form>[0]['layout'];

const Viewer: NextPage = () => {
  const [validation, setValidation] = useState({ status: true, message: ''})
  const [docUrl, setDocUrl] = useState<string>('')
  
  const fileToDataURL  = (file: File) => {
    return new Promise((resolve, _) => {
      const FR = new FileReader();
      FR.onloadend = () => resolve(FR.result)

      FR.readAsArrayBuffer(file)
    })  
  }

  const validType = (type: string): boolean => {
    const fileType: string = type.split("/").pop() || ''

    const validTypes = ["pdf"];
    if (validTypes.indexOf(fileType) === -1) {
      return false;
    }
    return true;
  }

  const onFileChange = async (event: any) => {
    const file: File = event.target.files[0]

    if (!file) return

    if (!validType(file.type)) {
      setValidation({ status: false, message: 'Invalid file type, only support pdf' })
      return
    }

    const arrayBuffer:  any = await fileToDataURL(event.target.files[0])
    const bytes  = new Uint8Array( arrayBuffer ); 
    const blob   = new Blob( [ bytes ], { type: "application/pdf" } );
    const url = URL.createObjectURL( blob );

    setDocUrl(url)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pdf Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      { validation?.status == false ? <Row><Alert message={validation?.message} type="error" showIcon /> </Row>: <></> }
        <Space>
          <div>
            <Input type='file' onChange={onFileChange} placeholder='Upload your file.'></Input>
          </div>          
        </Space>
        <Space className={ui.m_top}>
          { docUrl !== '' ? <iframe src={docUrl} style={
              { 
                width: 850, 
                height: 1100 
              }
            } frameBorder="0" scrolling="auto"  /> : <></>}
        </Space>
      </main>
    </div>
  )
}

export default Viewer