import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Welcome from '../component/welcome'
import { Menu, Layout } from 'antd';
import { AppstoreOutlined } from '@ant-design/icons';
const { Header, Content, Footer } = Layout;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple Thing, Also Useless </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout className="layout">
        <Header>
          <Menu mode="horizontal" defaultSelectedKeys={['mail']}>
            <Menu.SubMenu key="SubMenu" title="Navigation Two - Submenu" icon={<AppstoreOutlined />}>
              <Menu.Item key="one" icon={<AppstoreOutlined />}>
                <Link href="/pdf/viewer">
                  <a> Pdf Viewer </a>
                </Link>
              </Menu.Item>
              <Menu.Item key="two" icon={<AppstoreOutlined />}>
                <Link href="/pdf/nano-coverter">
                  <a>Converter to Hell</a>
                </Link>
              </Menu.Item>
              <Menu.Item key="thre  e" icon={<AppstoreOutlined />}>
                <Link href="/pdf/nano-coverter">
                  <a>Converter to Jail</a>
                </Link>
              </Menu.Item>
            </Menu.SubMenu>
          </Menu>
        </Header>

        <Content style={{ padding: '0 50px' }}>
          <Welcome></Welcome>
        </Content>
      </Layout>


      {/* <main className={styles.main}> */}
       
      {/* </main> */}
    </div>
  )
}

export default Home
