import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Welcome from '../component/welcome'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple Thing, Also Useless </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Welcome></Welcome>

        <div className={styles.grid}>
          <a href="/pdf/viewer" className={styles.card}>
            <h2>Pdf Viewer &rarr;</h2>
            <p>Find in-depth how to view pdf shitly and get desired coordinate</p>
          </a>

          <a href="/pdf/nano-coverter" className={styles.card}>
            <h2>Convert to Hell &rarr;</h2>
            <p>Convert Lower Left Y, Lower Left X, Upper Right Y, Upper Right X to X Y coordinate</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Convert to Jail &rarr;</h2>
            <p>Convert X Y coordinate to Lower Left Y, Lower Left X, Upper Right Y, Upper Right X.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
